version: "3.9"
services:
  web:
    container_name: ocm-flask
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - ./flaskr:/online-course-manager
    ports:
      - 5000:5000
  db:
    container_name: ocm-postgres
    image: "postgres:14.3"
    env_file: .env
    restart: always
  explorer:
    container_name: ocm-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
