name: Production Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ self-hosted, production ]
    steps:
    # need checkout before using compose-action
    - uses: actions/checkout@v3

    # re-build docker containers and restart if necessary
    - name: Update And Build Docker Containers
      run: docker-compose -f docker-compose.prod.yml up -d --build
