name: Production Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ self-hosted, production ]
    steps:
    # need checkout before using compose-action
    - uses: actions/checkout@v3

    # Create .env file
    - name: Create .env file
      run: echo "${{ secrets.PRODUCTION_DOTENV }}" > .env

    # re-build docker containers and restart if necessary
    # "docker compose" instead of "docker-compose" is due different
    # compose versions on the production server and locally
    - name: Update And Build Docker Containers
      run: docker compose -f docker-compose.prod.yml up -d --build
